#!/bin/bash

rsync -avHh --stats \
        --timeout 7200 \
        --include "*-live/" \
        --exclude "*.iso" \
	--exclude-from=$RSYNC_EXCLUDE \
        $SOURCE $TARGET/

DIR="/srv/$(hostname -f)/www/.sdb1/debian-cd/current/"
arch="amd64 armel i386 kfreebsd-amd64 kfreebsd-i386"
#arch=$(ls /ftp/debian-cd/current)
tempDir="/ftp/.sdb1/.temp/"

if [ ! -d $tempDir ]; then
        mkdir -p $tempDir
fi

for a in $arch
        do
        mkdir $tempDir/$a/ -p
        echo -e "Jigdoing $a CD Set"
        type="dvd"
        for b in $type
                do
                echo "Jigdoing $a $b"
                cat > $tempDir/"debian-$a-$b.conf" <<EOF
jigdoDir=$DIR/$a/jigdo-$b/
imageDir=$DIR/$a/iso-$b/
tmpDir=$tempDir/$a/
templateDir=$DIR/$a/jigdo-$b/
logfile=/srv/$(hostname -f)/status/log/sync/debian-cd/current/$a.$b.log
EOF
# Disabled due high load, please enable when debian releases new version
#                jigdo-mirror $tempDir/"debian-$a-$b.conf"
        done
#       jigdo-lite --noask ../"jigdo-cd"/*.jigdo
 #       cd $DIR/$a/"iso-dvd"/
  #      jigdo-lite --noask ../"jigdo-dvd"/*.jigdo
done
rsync -avHh --stats \
        --timeout 7200 --size-only --delete \
	--exclude-from=$RSYNC_EXCLUDE --delete-excluded \
        $SOURCE $TARGET

echo "Done"
echo $(date -u) > $DIR/trace/$(hostname -f)

