#!/bin/bash
debmirror -passive \
--host=download.virtualbox.org \
--root=virtualbox/debian \
--method=http \
--progress --dist=dapper,hardy,intrepid,lenny,etch,jaunty \
--section=non-free \
--arch=i386,amd64 \
--nosource \
--ignore-release-gpg --ignore-missing-release \
--ignore-release-gpg \
/ftp/misc/virtualbox
